apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-week10-client-deployment
  labels:
    app: devops-week10-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-week10-client
  template:
    metadata:
      labels:
        app: devops-week10-client
    spec:
      containers:
        - name: devops-week10-client
          image: 0100ulquiorra/yolo-client:1.0.0
          tty: true
          ports:
            - containerPort: 3000
