version: '3'
services:
  app:
    container_name: yolo_client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      - backend
  backend:
    container_name: yolo_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: 'mongodb+srv://Derrick:GuessWhat@gallery.iq1mgvs.mongodb.net/?retryWrites=true&w=majorityongodb://localhost:27017/'
    volumes:
      - test-vol:/data/db

volumes:
  test-vol: