version: '3'

services:
  backend:
    container_name: backend_container
    image: 0100ulquiorra/devops-week10-backend:1.0.0
    ports:
      - 6000:6000
    volumes:
      - ./backend/:/app
    depends_on:
      - mongo
    environment:
      PORT: 6000
      MONGO_URI: ''
  client:
    container_name: client_container
    image: 0100ulquiorra/devops-week10-client:1.0.0
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - backend
    environment:
      PORT: 3000
  mongo:
    container_name: database_container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USER: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    volumes:
      - test-vol:/data/db
volumes:
  test-vol:

    