version: '3'
services:
  client:
    container_name: yolo_client
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      yolo-network:
        ipv4_address: 172.20.0.4
  backend:
    container_name: yolo_backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    environment:
      PORT: 6005
      MONGODB_URI: 'mongodb+srv://Derrick:GuessWhat@cluster0.9g4d0eq.mongodb.net/?retryWrites=true&w=majority'
    volumes:
      - test-vol:/data/db
    depends_on:
      - mongo
    networks:
      yolo-network:
        ipv4_address: 172.20.0.3
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Derrick
      MONGO_INITDB_ROOT_PASSWORD: GuessWhat
    ports:
      - 27010:27010
    networks:
      yolo-network:
        ipv4_address: 172.20.0.2

networks:
  yolo-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  test-vol: